[package]
name = "wallet_project_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.10"
ic-cdk = "0.15.0"
ic-cdk-macros = "0.15.0"
serde = "1.0.204"